services:
  
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    networks:
      - network-bridge
    
  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    environment:
        NGROK_PROTOCOL: http
        NGROK_PORT: app:5000
        NGROK_AUTH: ${NGROK_AUTH}
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge