name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v4
    - name: Remove Docker Compose 
      run: docker compose down
    - name: Build the Docker Compose
      run: docker compose up --build --detach
    - name: Funnel Service app-ts Start
      run: docker compose exec app-ts tailscale funnel --bg 5000
